[package]
name = "kirkkaus"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
egui_extras = { version = "0.33.3", features = ["all_loaders"] }
env_logger = "0.11.8"
image = { version = "0.25", features = ["jpeg", "png"] }
log = "0.4.29"
